const productDatabase = [
    // --- Dados da Base Atualizada ---
    { "cod": 3, "client": "SILGAN", "name": "ROSCA BAIXA P2000 28 400 ESTRIADA BRANCO 767", "cavities": 48, "cycle": 33, "weight": 2.09, "pieces_per_hour_goal": 4265, "mp": "" },
    { "cod": 4, "client": "SILGAN", "name": "ROSCA BAIXA P2000 28 400 ESTRIADA OURO CB101", "cavities": 48, "cycle": 33, "weight": 2.09, "pieces_per_hour_goal": 4265, "mp": "" },
    { "cod": 6, "client": "SILGAN", "name": "ROSCA ALTA P2000 28 410 FOSCA BRANCA CB124", "cavities": 24, "cycle": 21.15, "weight": 3.18, "pieces_per_hour_goal": 3352, "mp": "" },
    { "cod": 7, "client": "SILGAN", "name": "ROSCA ALTA P2000 28 410 FOSCA BRANCA 767", "cavities": 24, "cycle": 21.15, "weight": 3.18, "pieces_per_hour_goal": 3352, "mp": "" },
    { "cod": 12, "client": "SILGAN", "name": "ROSCA ALTA P2000 28 410 ESTRIADA NATURAL", "cavities": 24, "cycle": 21.15, "weight": 3.18, "pieces_per_hour_goal": 3352, "mp": "" },
    { "cod": 15, "client": "SILGAN", "name": "ROSCA ALTA P2000 28 410 FOSCA AZUL CB150", "cavities": 24, "cycle": 21.15, "weight": 3.18, "pieces_per_hour_goal": 3352, "mp": "" },
    { "cod": 17, "client": "SILGAN", "name": "ROSCA ALTA P2000 28 410 FOSCA PRETO 017", "cavities": 24, "cycle": 21.15, "weight": 3.18, "pieces_per_hour_goal": 3352, "mp": "" },
    { "cod": 24, "client": "SILGAN", "name": "ANEL TRAVA P2000 STD NATURAL PP BRILHANTE", "cavities": 16, "cycle": 13.4, "weight": 0.38, "pieces_per_hour_goal": 3418, "mp": "" },
    { "cod": 25, "client": "SILGAN", "name": "ANEL TRAVA P2000 STD OURO CB101 PP BRILHANTE", "cavities": 16, "cycle": 13.4, "weight": 0.38, "pieces_per_hour_goal": 3418, "mp": "" },
    { "cod": 31, "client": "SILGAN", "name": "ANEL TRAVA P2000 STD AZUL CB150 PP TEXT", "cavities": 16, "cycle": 13.4, "weight": 0.38, "pieces_per_hour_goal": 3418, "mp": "" },
    { "cod": 32, "client": "SILGAN", "name": "ANEL TRAVA P2000 STD BRANCO 767 PP TEXT", "cavities": 16, "cycle": 13.4, "weight": 0.38, "pieces_per_hour_goal": 3418, "mp": "" },
    { "cod": 33, "client": "SILGAN", "name": "ANEL TRAVA P2000 STD BRANCO CB124 PP TEXT", "cavities": 16, "cycle": 13.4, "weight": 0.38, "pieces_per_hour_goal": 3418, "mp": "" },
    { "cod": 37, "client": "SILGAN", "name": "ANEL TRAVA P2000 STD OURO CB149 PP TEXT", "cavities": 16, "cycle": 13.4, "weight": 0.38, "pieces_per_hour_goal": 3418, "mp": "" },
    { "cod": 39, "client": "SILGAN", "name": "ANEL TRAVA P2000 STD PRETO 17 PP TEXT", "cavities": 16, "cycle": 13.4, "weight": 0.38, "pieces_per_hour_goal": 3418, "mp": "" },
    { "cod": 69, "client": "SILGAN", "name": "ATUADOR P2000 SATIN AZUL CB150 PP", "cavities": 24, "cycle": 19, "weight": 1.54, "pieces_per_hour_goal": 3874, "mp": "" },
    { "cod": 70, "client": "SILGAN", "name": "ATUADOR P2000 SATIN BRANCO 767 PP", "cavities": 24, "cycle": 19, "weight": 1.54, "pieces_per_hour_goal": 3874, "mp": "" },
    { "cod": 71, "client": "SILGAN", "name": "ATUADOR P2000 SATIN BRANCO CB124 PP", "cavities": 24, "cycle": 19, "weight": 1.54, "pieces_per_hour_goal": 3874, "mp": "" },
    { "cod": 75, "client": "SILGAN", "name": "ATUADOR P2000 SATIN NATURAL PP", "cavities": 24, "cycle": 19, "weight": 1.54, "pieces_per_hour_goal": 3874, "mp": "" },
    { "cod": 77, "client": "SILGAN", "name": "ATUADOR P2000 SATIN OURO CB101 PP", "cavities": 24, "cycle": 19, "weight": 1.54, "pieces_per_hour_goal": 3874, "mp": "" },
    { "cod": 78, "client": "SILGAN", "name": "ATUADOR P2000 SATIN OURO CB149 PP", "cavities": 24, "cycle": 19, "weight": 1.54, "pieces_per_hour_goal": 3874, "mp": "" },
    { "cod": 80, "client": "SILGAN", "name": "ATUADOR P2000 SATIN PRETO 17 PP", "cavities": 24, "cycle": 19, "weight": 1.54, "pieces_per_hour_goal": 3874, "mp": "" },
    { "cod": 91, "client": "SILGAN", "name": "BUCHA P2000 2ML NATURAL PP", "cavities": 32, "cycle": 20, "weight": 0.9, "pieces_per_hour_goal": 6120, "mp": "PP - FT120" },
    { "cod": 92, "client": "SILGAN", "name": "ACUMULADOR P2000 28MM NAT PP", "cavities": 32, "cycle": 19, "weight": 2.6, "pieces_per_hour_goal": 5137, "mp": "" },
    { "cod": 93, "client": "SILGAN", "name": "ACUMULADOR P2000 JUNTA-A NATURAL", "cavities": 32, "cycle": 19, "weight": 2.6, "pieces_per_hour_goal": 5137, "mp": "" },
    { "cod": 94, "client": "SILGAN", "name": "TAMPA MKIV MD STD NATURAL PP", "cavities": 16, "cycle": 10.5, "weight": 1.05, "pieces_per_hour_goal": 4080, "mp": "" },
    { "cod": 97, "client": "SILGAN", "name": "RETENTOR MKIV MD M300 STD NAT POM - 24 CAVS", "cavities": 24, "cycle": 15.5, "weight": 0.17, "pieces_per_hour_goal": 4541, "mp": "" },
    { "cod": 102, "client": "SILGAN", "name": "ATUADOR MKIV STD AZUL CB72 PP", "cavities": 32, "cycle": 30.4, "weight": 0.98, "pieces_per_hour_goal": 3040, "mp": "" },
    { "cod": 103, "client": "SILGAN", "name": "ATUADOR MKIV STD BRANCO 767 PP", "cavities": 32, "cycle": 30.4, "weight": 0.98, "pieces_per_hour_goal": 3040, "mp": "" },
    { "cod": 104, "client": "SILGAN", "name": "ATUADOR MKIV STD BRANCO ANIL 2902 PP", "cavities": 32, "cycle": 30.4, "weight": 0.98, "pieces_per_hour_goal": 3040, "mp": "" },
    { "cod": 109, "client": "SILGAN", "name": "ATUADOR MKIV STD NATURAL PP", "cavities": 32, "cycle": 30.4, "weight": 0.98, "pieces_per_hour_goal": 3040, "mp": "" },
    { "cod": 111, "client": "SILGAN", "name": "ATUADOR MKIV STD PRETO 17 PP", "cavities": 32, "cycle": 30.4, "weight": 0.98, "pieces_per_hour_goal": 3040, "mp": "" },
    { "cod": 112, "client": "SILGAN", "name": "ATUADOR MKIV STD ROSA CB79 PP", "cavities": 32, "cycle": 30.4, "weight": 0.98, "pieces_per_hour_goal": 3040, "mp": "" },
    { "cod": 114, "client": "SILGAN", "name": "ATUADOR MKIV STD ROXO CB144 PP", "cavities": 32, "cycle": 30.4, "weight": 0.98, "pieces_per_hour_goal": 3040, "mp": "" },
    { "cod": 175, "client": "SILGAN", "name": "RETENTOR M300 STD NAT POM - 64 CAVIDADES", "cavities": 64, "cycle": 20.5, "weight": 0.17, "pieces_per_hour_goal": 8078, "mp": "" },
    { "cod": 176, "client": "SILGAN", "name": "ACUMULADOR M300 STANDARD NAT PP", "cavities": 48, "cycle": 25, "weight": 1, "pieces_per_hour_goal": 5630, "mp": "" },
    { "cod": 206, "client": "SILGAN", "name": "CAPSULA MELODIE CLIKIT 17 NAT PP", "cavities": 16, "cycle": 16, "weight": 0.5, "pieces_per_hour_goal": 3060, "mp": "" },
    { "cod": 207, "client": "SILGAN", "name": "CAPSULA MELODIE CLIKIT 18 NAT PP", "cavities": 16, "cycle": 16, "weight": 0.52, "pieces_per_hour_goal": 3060, "mp": "" },
    { "cod": 233, "client": "GERDAU", "name": "TRAVA DO CARRETEL", "cavities": 2, "cycle": 22, "weight": 4.64, "pieces_per_hour_goal": 278, "mp": "" },
    { "cod": 234, "client": "GERDAU", "name": "ADAPTADOR POLIPROPILENO PARA CARRETEL", "cavities": 1, "cycle": 60, "weight": 222.33, "pieces_per_hour_goal": 51, "mp": "" },
    { "cod": 235, "client": "GERDAU", "name": "CARRETEL - OVD (SEM INSCRIÇÃO - C/ ETIQUETA)", "cavities": 1, "cycle": 60, "weight": 222.33, "pieces_per_hour_goal": 51, "mp": "" },
    { "cod": 236, "client": "ÓRICA", "name": "J-HOOK LONG BLUE (CLIP AZUL)", "cavities": 6, "cycle": 18, "weight": 3.7, "pieces_per_hour_goal": 1020, "mp": "" },
    { "cod": 237, "client": "ÓRICA", "name": "SHELL PLASTIC EXEL™ YELLOW 17MS (CONECT. AMARELO)", "cavities": 4, "cycle": 30, "weight": 14.38, "pieces_per_hour_goal": 408, "mp": "" },
    { "cod": 238, "client": "ÓRICA", "name": "CORPO PLAST EXEL MS/DCD (COR AZUL 65 MS)", "cavities": 4, "cycle": 30, "weight": 14.38, "pieces_per_hour_goal": 408, "mp": "" },
    { "cod": 239, "client": "ÓRICA", "name": "SHELL PLASTIC EXEL™ WHITE 42MS (CONECT. BRANCO)", "cavities": 4, "cycle": 30, "weight": 14.38, "pieces_per_hour_goal": 408, "mp": "" },
    { "cod": 240, "client": "ÓRICA", "name": "SHELL PLASTIC EXEL™ MSC ORANGE 100MS (CONECT. LARANJA)", "cavities": 4, "cycle": 30, "weight": 14.38, "pieces_per_hour_goal": 408, "mp": "" },
    { "cod": 242, "client": "ÓRICA", "name": "SHELL PLASTIC EXEL™ GREEN 9MS (CONECT. VERDE)", "cavities": 4, "cycle": 30, "weight": 14.38, "pieces_per_hour_goal": 408, "mp": "" },
    { "cod": 243, "client": "ÓRICA", "name": "SHELL PLASTIC EXEL™ RED 25MS (CONECT. VERMELHO)", "cavities": 4, "cycle": 30, "weight": 14.38, "pieces_per_hour_goal": 408, "mp": "" },
    { "cod": 257, "client": "PARKER", "name": "TAMPA PLASTICA SEM FURO", "cavities": 4, "cycle": 21, "weight": 12.25, "pieces_per_hour_goal": 583, "mp": "" },
    { "cod": 258, "client": "PARKER", "name": "TAMPA PLASTICA COM FURO", "cavities": 4, "cycle": 21, "weight": 15.49, "pieces_per_hour_goal": 583, "mp": "" },
    { "cod": 259, "client": "PARKER", "name": "BOCAL PARA FILTRO DE OLEO", "cavities": 4, "cycle": 23, "weight": 7.75, "pieces_per_hour_goal": 532, "mp": "" },
    { "cod": 260, "client": "PARKER", "name": "PISTAO PARA FILTRO DE OLEO", "cavities": 4, "cycle": 23, "weight": 5.3, "pieces_per_hour_goal": 532, "mp": "" },
    { "cod": 261, "client": "PARKER", "name": "TAMPA PLASTICA 5831", "cavities": 4, "cycle": 35, "weight": 33.02, "pieces_per_hour_goal": 349, "mp": "" },
    { "cod": 262, "client": "PARKER", "name": "COROA PARA FILTRO DE OLEO", "cavities": 2, "cycle": 18, "weight": 0.52, "pieces_per_hour_goal": 340, "mp": "" },
    { "cod": 263, "client": "PARKER", "name": "ADAPTADOR", "cavities": 2, "cycle": 18, "weight": 21.88, "pieces_per_hour_goal": 340, "mp": "" },
    { "cod": 264, "client": "PARKER", "name": "SUPORTE PLASTICO SERIE 600 ESCAL (COM ABA)", "cavities": 4, "cycle": 50, "weight": 51.94, "pieces_per_hour_goal": 245, "mp": "" },
    { "cod": 265, "client": "PARKER", "name": "SUPORTE PLASTICO SERIE R260 (SEM ABA)", "cavities": 4, "cycle": 50, "weight": 41, "pieces_per_hour_goal": 245, "mp": "" },
    { "cod": 266, "client": "PARKER", "name": "PLUG 1/4 - 225 PARA FILTRO DE OLEO", "cavities": 1, "cycle": 20, "weight": 3.7, "pieces_per_hour_goal": 153, "mp": "" },
    { "cod": 267, "client": "PARKER", "name": "TAMPA PLASTICA 4 CAVIDADES", "cavities": 4, "cycle": 50, "weight": 47.29, "pieces_per_hour_goal": 245, "mp": "" },
    { "cod": 268, "client": "PARKER", "name": "TAMPA PLASTICA 5923 - DUPONT", "cavities": 4, "cycle": 40, "weight": 22.39, "pieces_per_hour_goal": 306, "mp": "" },
    { "cod": 273, "client": "PARKER", "name": "TAMPAO PLASTICO AMARELO (MONTADO) P/ FILTRO DE OLEO", "cavities": 4, "cycle": 18, "weight": 3.64, "pieces_per_hour_goal": 680, "mp": "" },
    { "cod": 274, "client": "PARKER", "name": "TAMPAO PLASTICO NATURAL (MONTADO) P/ FILTRO DE OLEO", "cavities": 4, "cycle": 18, "weight": 3.64, "pieces_per_hour_goal": 680, "mp": "" },
    { "cod": 276, "client": "PARKER", "name": "PLUG 1/2\" 225 P/ F OLEO COM ORING", "cavities": 1, "cycle": 20, "weight": 2.94, "pieces_per_hour_goal": 153, "mp": "" },
    { "cod": 277, "client": "PARKER", "name": "CONICO FILTRO OLEO", "cavities": 1, "cycle": 60, "weight": 27, "pieces_per_hour_goal": 51, "mp": "" },
    { "cod": 278, "client": "PARKER", "name": "TURBINA (MONTADA) P/ FILTRO DE OLEO", "cavities": 1, "cycle": 60, "weight": 65.09, "pieces_per_hour_goal": 51, "mp": "" },
    { "cod": 279, "client": "PARKER", "name": "CONJUNTO TAMPAO (MONTADO)", "cavities": 2, "cycle": 20, "weight": 3.44, "pieces_per_hour_goal": 306, "mp": "" },
    { "cod": 280, "client": "PARKER", "name": "PLUG DO DRENO + VEDADOR", "cavities": 2, "cycle": 30, "weight": 7.45, "pieces_per_hour_goal": 204, "mp": "" },
    { "cod": 436, "client": "APTAR", "name": "CLIP PLASTICO PP-RND DS25 K2/F3 OURO (MODIF)", "cavities": 16, "cycle": 16, "weight": 1.67, "pieces_per_hour_goal": 3060, "mp": "" },
    { "cod": 441, "client": "APTAR", "name": "CLIP PLASTICO PP-RND MA00 K2/F3 PRETO (MODIF)", "cavities": 16, "cycle": 16, "weight": 1.67, "pieces_per_hour_goal": 3060, "mp": "" },
    { "cod": 442, "client": "APTAR", "name": "CCLIPE-K--PP-NATU--RRNA00004", "cavities": 16, "cycle": 16, "weight": 1.67, "pieces_per_hour_goal": 3060, "mp": "" },
    { "cod": 452, "client": "APTAR", "name": "ATUADOR-EMII-PP--4,34-NATU---SPRAY", "cavities": 32, "cycle": 20, "weight": 1.09, "pieces_per_hour_goal": 4896, "mp": "" },
    { "cod": 453, "client": "APTAR", "name": "ATUADOR-EMII-PP--4,34-BLAC---SPRAY--MS06", "cavities": 32, "cycle": 20, "weight": 1.09, "pieces_per_hour_goal": 4896, "mp": "" },
    { "cod": 454, "client": "APTAR", "name": "ATUADOR - EMII-PP--4,34-BLUE---SPRAY--KS24", "cavities": 32, "cycle": 20, "weight": 1.09, "pieces_per_hour_goal": 4896, "mp": "" },
    { "cod": 455, "client": "APTAR", "name": "ATUADOR-EMII-PP--4,34-GREE---SPRAY-GS18", "cavities": 32, "cycle": 20, "weight": 1.09, "pieces_per_hour_goal": 4896, "mp": "" },
    { "cod": 456, "client": "APTAR", "name": "ATUADOR-EMII-PP--4,34-BROW---SPRAY--HS11", "cavities": 32, "cycle": 20, "weight": 1.09, "pieces_per_hour_goal": 4896, "mp": "" },
    { "cod": 457, "client": "APTAR", "name": "TAMPA-EM-28,20-PP-NATU--SHNY-----EM STD", "cavities": 32, "cycle": 12, "weight": 1.15, "pieces_per_hour_goal": 8160, "mp": "" },
    { "cod": 458, "client": "APTAR", "name": "TAMPA-EM-28,20-PP-BLAC--SHNY", "cavities": 32, "cycle": 12, "weight": 1.15, "pieces_per_hour_goal": 8160, "mp": "" },
    { "cod": 459, "client": "APTAR", "name": "ATUADOR-EMII-PP--4,34-ORAN-SHNY--SPRAY", "cavities": 32, "cycle": 20, "weight": 1.09, "pieces_per_hour_goal": 4896, "mp": "" },
    { "cod": 464, "client": "APTAR", "name": "ATUADOR-EMII-PP--4,34-WHIT---SPRAY", "cavities": 32, "cycle": 20, "weight": 1.09, "pieces_per_hour_goal": 4896, "mp": "" },
    { "cod": 477, "client": "APTAR", "name": "CLIP PLASTICO BRANCO CA01 K2/F3", "cavities": 16, "cycle": 16, "weight": 1.67, "pieces_per_hour_goal": 3060, "mp": "" },
    { "cod": 478, "client": "APTAR", "name": "ATUADOR-EMII-PP--4,34-PINK---SPRAY--ES30", "cavities": 32, "cycle": 20, "weight": 1.09, "pieces_per_hour_goal": 4896, "mp": "" },
    { "cod": 534, "client": "APTAR", "name": "ACT EM CLASSIC PP MINT GREEN 1702395-SE", "cavities": 32, "cycle": 20, "weight": 1.09, "pieces_per_hour_goal": 4896, "mp": "" },
    { "cod": 543, "client": "SILGAN", "name": "ROSCA P2000 24 410 LISA PRETO PP", "cavities": 24, "cycle": 21.15, "weight": 2.28, "pieces_per_hour_goal": 3352, "mp": "" },
    { "cod": 574, "client": "LH COLUS", "name": "MANOPLA MACA (HANDLER)", "cavities": 1, "cycle": 60, "weight": 77, "pieces_per_hour_goal": 51, "mp": "" },
    { "cod": 575, "client": "LH COLUS", "name": "BARRA TRIPLA CORREDIÇA (SLIDE THREE BAR)", "cavities": 1, "cycle": 30, "weight": 11.68, "pieces_per_hour_goal": 102, "mp": "" },
    { "cod": 865, "client": "PARKER", "name": "TURBINA 2 PARA FILTRO DE OLEO", "cavities": 1, "cycle": 60, "weight": 40.74, "pieces_per_hour_goal": 51, "mp": "" },
    { "cod": 866, "client": "PARKER", "name": "TURBINA 1 PARA FILTRO DE OLEO", "cavities": 1, "cycle": 60, "weight": 24.35, "pieces_per_hour_goal": 51, "mp": "" },
    { "cod": 891, "client": "PARKER", "name": "TAMPAO PLASTICO P/ FILTRO DE OLEO AMARELO (SEM O'RING)", "cavities": 4, "cycle": 18, "weight": 3.36, "pieces_per_hour_goal": 680, "mp": "" },
    { "cod": 892, "client": "PARKER", "name": "TAMPAO PLASTICO P/ FILTRO DE OLEO NATURAL (SEM O'RING)", "cavities": 4, "cycle": 18, "weight": 3.36, "pieces_per_hour_goal": 680, "mp": "" },
    { "cod": 893, "client": "PARKER", "name": "PLUG 1/2\" 225 P/ F OLEO (SEM O'RING)", "cavities": 1, "cycle": 20, "weight": 2.84, "pieces_per_hour_goal": 153, "mp": "" },
    { "cod": 894, "client": "PARKER", "name": "CONJUNTO TAMPÃO (SEM O'RING)", "cavities": 2, "cycle": 20, "weight": 2.8, "pieces_per_hour_goal": 306, "mp": "" },
    { "cod": 895, "client": "PARKER", "name": "PLUG DO DRENO (SEM VEDADOR)", "cavities": 2, "cycle": 30, "weight": 7.35, "pieces_per_hour_goal": 204, "mp": "" },
    { "cod": 904, "client": "APTAR", "name": "TAMPA-EM-28,20-PP-BLAC--SHNY-----EM STD", "cavities": 32, "cycle": 12, "weight": 1.15, "pieces_per_hour_goal": 8160, "mp": "" },
    { "cod": 905, "client": "APTAR", "name": "CLIP PLASTICO PP-RND DS10 K2/F3 DOURADO (MODIF)", "cavities": 16, "cycle": 16, "weight": 1.67, "pieces_per_hour_goal": 3060, "mp": "" },
    { "cod": 921, "client": "APTAR", "name": "ATUADOR-EMII-PP--4,34-RED---SPRAY--ES38", "cavities": 32, "cycle": 20, "weight": 1.09, "pieces_per_hour_goal": 4896, "mp": "" },
    { "cod": 936, "client": "APTAR", "name": "ATUADOR-EMII-PP--4,34-RED-SHNY--SPRAY-A3", "cavities": 32, "cycle": 20, "weight": 1.09, "pieces_per_hour_goal": 4896, "mp": "" },
    { "cod": 948, "client": "APTAR", "name": "ATUADOR-EMII-PP--4,34-BLUE---SPRAY", "cavities": 32, "cycle": 20, "weight": 1.09, "pieces_per_hour_goal": 4896, "mp": "" },
    { "cod": 984, "client": "LH COLUS", "name": "CAPA POSTE CENTRAL", "cavities": 1, "cycle": 30, "weight": 3.3, "pieces_per_hour_goal": 102, "mp": "" },
    { "cod": 986, "client": "LH COLUS", "name": "SHIM SUPPORT LITTER (SUPORTE CALÇO MACA)", "cavities": 1, "cycle": 60, "weight": 8, "pieces_per_hour_goal": 51, "mp": "" },
    { "cod": 1005, "client": "APTAR", "name": "ATUADOR-EMII-PP--4,34-YELL---SPRAY--DS22", "cavities": 32, "cycle": 20, "weight": 1.09, "pieces_per_hour_goal": 4896, "mp": "" },
    { "cod": 1063, "client": "SILGAN", "name": "ROSCA M300 GL18 ESTRIADO NATURAL PP", "cavities": 32, "cycle": 33, "weight": 2.05, "pieces_per_hour_goal": 2689, "mp": "" },
    { "cod": 1623, "client": "SILGAN", "name": "TAMPA MKIV MD STD PRETA PP", "cavities": 16, "cycle": 10.5, "weight": 1.05, "pieces_per_hour_goal": 4080, "mp": "" },
    { "cod": 1912, "client": "PARKER", "name": "SUPORTE PLASTICO", "cavities": 2, "cycle": 30.4, "weight": 48.2, "pieces_per_hour_goal": 201, "mp": "" },
    { "cod": 2206, "client": "PARKER", "name": "SUPORTE DO COPO NOVO - 6 CAVIDADES - NYLON", "cavities": 6, "cycle": 50, "weight": 56, "pieces_per_hour_goal": 367, "mp": "" },
    { "cod": 2294, "client": "PARKER", "name": "SUPORTE DO COPO NOVO - 6 CAVIDADES - TECHNYL", "cavities": 6, "cycle": 50, "weight": 56, "pieces_per_hour_goal": 367, "mp": "" },
    { "cod": 2308, "client": "PARKER", "name": "SUPORTE DO COPO NOVO - 6 CAVIDADES - LANXESS", "cavities": 6, "cycle": 50, "weight": 56, "pieces_per_hour_goal": 367, "mp": "" },
    { "cod": 2563, "client": "SILGAN", "name": "ROSCA BAIXA P2000 28 400 ESTRIADA NATURAL", "cavities": 48, "cycle": 33, "weight": 2.09, "pieces_per_hour_goal": 4265, "mp": "" },
    { "cod": 2704, "client": "SILGAN", "name": "ROSCA P2000 24 410 LISA BRANCA 767 PP", "cavities": 24, "cycle": 21.15, "weight": 2.28, "pieces_per_hour_goal": 3352, "mp": "" },
    { "cod": 2998, "client": "SILGAN", "name": "ROSCA ALTA P2000 28 410 FOSCA AZUL CB236 PP", "cavities": 24, "cycle": 21.15, "weight": 3.18, "pieces_per_hour_goal": 3352, "mp": "" },
    { "cod": 2999, "client": "SILGAN", "name": "ANEL TRAVA P2000 STD AZUL CB236 PP TEXT", "cavities": 16, "cycle": 13.4, "weight": 0.38, "pieces_per_hour_goal": 3418, "mp": "" },
    { "cod": 3000, "client": "SILGAN", "name": "ATUADOR P2000 SATIN AZUL CB236 PP", "cavities": 24, "cycle": 19, "weight": 1.54, "pieces_per_hour_goal": 3874, "mp": "" },
    { "cod": 3052, "client": "SILGAN", "name": "ROSCA P2000 24 410 LISA CHUMBO CB194 PP", "cavities": 24, "cycle": 21.15, "weight": 2.28, "pieces_per_hour_goal": 3352, "mp": "" },
    { "cod": 3054, "client": "SILGAN", "name": "ATUADOR P2000 SATIN CHUMBO CB194 PP", "cavities": 24, "cycle": 19, "weight": 1.54, "pieces_per_hour_goal": 3874, "mp": "" },
    { "cod": 3202, "client": "SILGAN", "name": "ATUADOR MKIV STD BRONZE CB245 PP", "cavities": 32, "cycle": 30.4, "weight": 0.98, "pieces_per_hour_goal": 3040, "mp": "" },
    { "cod": 3204, "client": "SILGAN", "name": "TAMPA MKIV MD BRONZE CB245 PP", "cavities": 16, "cycle": 10.5, "weight": 1.05, "pieces_per_hour_goal": 4080, "mp": "" },
    { "cod": 3442, "client": "JORNADA", "name": "CONECTOR MODELO V CINZA MOLDE 1 - 30°", "cavities": 4, "cycle": 26, "weight": 0.88, "pieces_per_hour_goal": 471, "mp": "" },
    { "cod": 3443, "client": "JORNADA", "name": "CONECTOR MODELO R VERDE MOLDE 2 - 120°", "cavities": 8, "cycle": 26, "weight": 0.97, "pieces_per_hour_goal": 942, "mp": "" },
    { "cod": 3444, "client": "JORNADA", "name": "CONECTOR MODELO L AMARELO MOLDE 2 - 90°", "cavities": 8, "cycle": 26, "weight": 0.94, "pieces_per_hour_goal": 824, "mp": "" },
    { "cod": 3445, "client": "JORNADA", "name": "CONECTOR MODELO X MARROM MOLDE 1 - CRUZ (360°)", "cavities": 4, "cycle": 26, "weight": 1.72, "pieces_per_hour_goal": 235, "mp": "" },
    { "cod": 3446, "client": "HOKKAIDO", "name": "CONECTOR MODELO T AZUL MOLDE 3 - (180°/90°)", "cavities": 8, "cycle": 26, "weight": 1.33, "pieces_per_hour_goal": 942, "mp": "" },
    { "cod": 3447, "client": "HOKKAIDO", "name": "CONECTOR MODELO I VERMELHO MOLDE 3 - RETO (180°)", "cavities": 8, "cycle": 26, "weight": 0.97, "pieces_per_hour_goal": 942, "mp": "" },
    { "cod": 3457, "client": "PARKER", "name": "TAMPA PLASTICA 5923 - DURETHAN", "cavities": 4, "cycle": 40, "weight": 22.39, "pieces_per_hour_goal": 306, "mp": "" },
    { "cod": 3503, "client": "PARKER", "name": "TAMPA SUPERIOR PARA FILTRO", "cavities": 2, "cycle": 40, "weight": 25.12, "pieces_per_hour_goal": 153, "mp": "" },
    { "cod": 3504, "client": "PARKER", "name": "TAMPA INFERIOR PARA FILTRO", "cavities": 2, "cycle": 40, "weight": 26.46, "pieces_per_hour_goal": 153, "mp": "" },
    { "cod": 3555, "client": "GERDAU", "name": "CARRETEL", "cavities": 1, "cycle": 60, "weight": 222.33, "pieces_per_hour_goal": 51, "mp": "" },
    { "cod": 3582, "client": "ÓRICA", "name": "SHELL PLASTIC EXEL™ LIGHTGREEN 200MS (CONECT. VERDE CLARO)", "cavities": 4, "cycle": 30, "weight": 14.38, "pieces_per_hour_goal": 408, "mp": "" },
    { "cod": 3698, "client": "SUNVISOR", "name": "COMEDOR DO GATO AZUL CLARO GLITTER", "cavities": 1, "cycle": 45, "weight": 91, "pieces_per_hour_goal": 68, "mp": "" },
    { "cod": 3700, "client": "SUNVISOR", "name": "COMEDOR DO GATO LARANJA GLITTER GLITTER", "cavities": 1, "cycle": 45, "weight": 91, "pieces_per_hour_goal": 68, "mp": "" },
    { "cod": 3701, "client": "SUNVISOR", "name": "COMEDOR DO GATO ROXO GLITTER", "cavities": 1, "cycle": 45, "weight": 91, "pieces_per_hour_goal": 68, "mp": "" },
    { "cod": 3702, "client": "SUNVISOR", "name": "COMEDOR DO GATO AZUL CLARO", "cavities": 1, "cycle": 45, "weight": 91, "pieces_per_hour_goal": 68, "mp": "" },
    { "cod": 3703, "client": "SUNVISOR", "name": "COMEDOR DO GATO BRANCO", "cavities": 1, "cycle": 45, "weight": 91, "pieces_per_hour_goal": 68, "mp": "" },
    { "cod": 3711, "client": "SUNVISOR", "name": "COMEDOR DO GATO AZUL CLARO GLITTER - H301", "cavities": 1, "cycle": 45, "weight": 91, "pieces_per_hour_goal": 68, "mp": "" },
    { "cod": 3712, "client": "SUNVISOR", "name": "COMEDOR DO GATO LARANJA GLITTER GLITTER - H301", "cavities": 1, "cycle": 45, "weight": 91, "pieces_per_hour_goal": 68, "mp": "" },
    { "cod": 3713, "client": "SUNVISOR", "name": "COMEDOR DO GATO ROXO GLITTER - H301", "cavities": 1, "cycle": 45, "weight": 91, "pieces_per_hour_goal": 68, "mp": "" },
    { "cod": 3714, "client": "SUNVISOR", "name": "COMEDOR DO GATO AZUL CLARO - H301", "cavities": 1, "cycle": 45, "weight": 91, "pieces_per_hour_goal": 68, "mp": "" },
    { "cod": 3715, "client": "SUNVISOR", "name": "COMEDOR DO GATO BRANCO - H301", "cavities": 1, "cycle": 45, "weight": 91, "pieces_per_hour_goal": 68, "mp": "" },
    { "cod": 3858, "client": "HOKKAIDO", "name": "POTE DE SORVETE BRANCO", "cavities": 1, "cycle": 9, "weight": 48.2, "pieces_per_hour_goal": 340, "mp": "" },
    { "cod": 3859, "client": "HOKKAIDO", "name": "TAMPA BRANCA DO POTE DE SORVETE", "cavities": 1, "cycle": 9, "weight": 22, "pieces_per_hour_goal": 340, "mp": "" },
    { "cod": 3860, "client": "HOKKAIDO", "name": "POTE DE SORVETE NATURAL", "cavities": 1, "cycle": 9, "weight": 48.2, "pieces_per_hour_goal": 340, "mp": "" },
    { "cod": 3861, "client": "HOKKAIDO", "name": "TAMPA NATURAL DO POTE DE SORVETE", "cavities": 1, "cycle": 9, "weight": 22, "pieces_per_hour_goal": 340, "mp": "" },
    { "cod": 4006, "client": "CSINFT", "name": "FACE INTERNA BRANCA CSI - PECA 1", "cavities": 1, "cycle": 42, "weight": 17, "pieces_per_hour_goal": 73, "mp": "" },
    { "cod": 4007, "client": "JORNADA", "name": "FACE EXTERNA BRANCA CSI - PECA 2", "cavities": 1, "cycle": 42, "weight": 11.5, "pieces_per_hour_goal": 73, "mp": "" },
    { "cod": 4008, "client": "JORNADA", "name": "TAMPÃO BRANCO CSI - PECA 3", "cavities": 1, "cycle": 42, "weight": 4, "pieces_per_hour_goal": 73, "mp": "" }
]

productDatabase.forEach(product => {
    if (typeof product.mp === 'undefined') {
        product.mp = '';
    }
});

// Adicionar ao database.js
const taraBoxesDatabase = {
    "H-01": { "peso": 0, "descricao": "caixa plastica" },
    "H-02": { "peso": 0, "descricao": "caixa plastica" },
    "H-03": { "peso": 0, "descricao": "caixa plastica" },
    "H-04": { "peso": 0, "descricao": "caixa plastica" },
    "H-05": { "peso": 0, "descricao": "caixa plastica" },
    "H-06": { "peso": 0, "descricao": "caixa plastica" },
    "H-07": { "peso": 0, "descricao": "caixa plastica" },
    "H-08": { "peso": 0, "descricao": "caixa plastica" },
    "H-09": { "peso": 0, "descricao": "caixa plastica" },
    "H-10": { "peso": 0, "descricao": "caixa plastica" },
    "H-11": { "peso": 0, "descricao": "caixa plastica" },
    "H-12": { "peso": 0, "descricao": "caixa plastica" },
    "H-13": { "peso": 0, "descricao": "caixa plastica" },
    "H-14": { "peso": 0, "descricao": "caixa plastica" },
    "H-15": { "peso": 0, "descricao": "caixa plastica" },
    "H-16": { "peso": 0, "descricao": "caixa plastica" },
    "H-17": { "peso": 0, "descricao": "caixa plastica" },
    "H-18": { "peso": 0, "descricao": "caixa plastica" },
    "H-19": { "peso": 0, "descricao": "caixa plastica" },
    "H-20": { "peso": 0, "descricao": "caixa plastica" },
    "H-26": { "peso": 0, "descricao": "caixa plastica" },
    "H-27": { "peso": 0, "descricao": "caixa plastica" },
    "H-28": { "peso": 0, "descricao": "caixa plastica" },
    "H-29": { "peso": 0, "descricao": "caixa plastica" },
    "H-30": { "peso": 0, "descricao": "caixa plastica" },
    "H-31": { "peso": 0, "descricao": "caixa plastica" },
    "H-32": { "peso": 0, "descricao": "caixa plastica" }
};

