const productDatabase = [
    // --- Dados da Base Original ---
    { "client": "SILGAN", "name": "ATUADOR DISPENSADOR", "cavities": 32, "cycle": 30.2, "weight": 0, "pieces_per_hour_goal": 3221 },
    { "client": "SILGAN", "name": "ATUADOR SPRAY", "cavities": 32, "cycle": 30.4, "weight": 0, "pieces_per_hour_goal": 3040 },
    { "client": "SILGAN", "name": "SOBRETAMPA", "cavities": 16, "cycle": 10.5, "weight": 0, "pieces_per_hour_goal": 4080 },
    { "client": "SILGAN", "name": "RETENTOR DA MOLA 24 CAV", "cavities": 24, "cycle": 15.5, "weight": 0, "pieces_per_hour_goal": 4541 },
    { "client": "SILGAN", "name": "ROSCA M300", "cavities": 32, "cycle": 33, "weight": 0, "pieces_per_hour_goal": 2689 },
    { "client": "SILGAN", "name": "ACUMULADOR M300", "cavities": 48, "cycle": 25, "weight": 0, "pieces_per_hour_goal": 5630 },
    { "client": "SILGAN", "name": "ROSCA BAIXA P2000", "cavities": 48, "cycle": 33, "weight": 0, "pieces_per_hour_goal": 4265 },
    { "client": "SILGAN", "name": "ANEL TRAVA BRILHANTE / TEXTURIZADA", "cavities": 16, "cycle": 13.4, "weight": 0, "pieces_per_hour_goal": 3418 },
    { "client": "SILGAN", "name": "BUCHA P2000", "cavities": 32, "cycle": 16, "weight": 0, "pieces_per_hour_goal": 6120 },
    { "client": "SILGAN", "name": "ACUMULADOR P2000", "cavities": 32, "cycle": 19, "weight": 0, "pieces_per_hour_goal": 5137 },
    { "client": "SILGAN", "name": "ROSCA ALTA P2000 28/410 FOSCA / ESTRIADA", "cavities": 24, "cycle": 21.15, "weight": 0, "pieces_per_hour_goal": 3352 },
    { "client": "SILGAN", "name": "ROSCA ALTA P2000 24/410 LISA", "cavities": 24, "cycle": 21.15, "weight": 0, "pieces_per_hour_goal": 3352 },
    { "client": "SILGAN", "name": "ATUADOR P2000", "cavities": 24, "cycle": 19, "weight": 0, "pieces_per_hour_goal": 3874 },
    { "client": "SILGAN", "name": "CLIKIT 17", "cavities": 16, "cycle": 16, "weight": 0, "pieces_per_hour_goal": 3060 },
    { "client": "SILGAN", "name": "RETENTOR DA MOLA 64 CAV", "cavities": 64, "cycle": 20.5, "weight": 0, "pieces_per_hour_goal": 8078 },
    { "client": "SILGAN", "name": "ROSCA MKIV 18/415", "cavities": 48, "cycle": 40, "weight": 0, "pieces_per_hour_goal": 3672 },
    { "client": "SILGAN", "name": "ROSCA MKIV 20/410", "cavities": 48, "cycle": 40, "weight": 0, "pieces_per_hour_goal": 3672 },
    { "client": "SILGAN", "name": "ROSCA MKIV 22/415", "cavities": 48, "cycle": 40, "weight": 0, "pieces_per_hour_goal": 3672 },
    { "client": "SILGAN", "name": "ROSCA MKIV 24/410", "cavities": 48, "cycle": 40, "weight": 0, "pieces_per_hour_goal": 3672 },
    { "client": "APTAR", "name": "CAPA KAIAK 8 CAVIDADES", "cavities": 8, "cycle": 16, "weight": 0, "pieces_per_hour_goal": 1530 },
    { "client": "APTAR", "name": "CAPA KAIAK 16 CAVIDADES", "cavities": 16, "cycle": 16, "weight": 0, "pieces_per_hour_goal": 3060 },
    { "client": "APTAR", "name": "CLIP K2", "cavities": 16, "cycle": 16, "weight": 0, "pieces_per_hour_goal": 3060 },
    { "client": "APTAR", "name": "CLIP Q3", "cavities": 8, "cycle": 17, "weight": 0, "pieces_per_hour_goal": 1440 },
    { "client": "APTAR", "name": "ROSCA SENTIDOS - MOLDE 1 (A)", "cavities": 24, "cycle": 36, "weight": 0, "pieces_per_hour_goal": 2040 },
    { "client": "APTAR", "name": "ROSCA SENTIDOS - MOLDE 2 (D)", "cavities": 24, "cycle": 36, "weight": 0, "pieces_per_hour_goal": 2040 },
    { "client": "APTAR", "name": "ATUADOR SENTIDOS / POEMA", "cavities": 24, "cycle": 25.5, "weight": 0, "pieces_per_hour_goal": 2880 },
    { "client": "APTAR", "name": "ROSCA 24/410 ESTRIADA / LISA - APTAR", "cavities": 16, "cycle": 18, "weight": 0, "pieces_per_hour_goal": 2720 },
    { "client": "APTAR", "name": "ATUADOR CLASSIC", "cavities": 32, "cycle": 20, "weight": 0, "pieces_per_hour_goal": 4896 },
    { "client": "APTAR", "name": "TAMPA EUROMIST", "cavities": 32, "cycle": 12, "weight": 0, "pieces_per_hour_goal": 8160 },
    { "client": "APTAR", "name": "ATUADOR A03L", "cavities": 56, "cycle": 18, "weight": 0, "pieces_per_hour_goal": 9520 },
    { "client": "APTAR", "name": "ATUADOR A46L", "cavities": 32, "cycle": 21, "weight": 0, "pieces_per_hour_goal": 4663 },
    { "client": "ÓRICA", "name": "CLIP", "cavities": 6, "cycle": 18, "weight": 0, "pieces_per_hour_goal": 1020 },
    { "client": "ÓRICA", "name": "CONECTOR", "cavities": 4, "cycle": 30, "weight": 0, "pieces_per_hour_goal": 408 },
    { "client": "PARKER", "name": "TAMPA BEGE SUPERIOR", "cavities": 2, "cycle": 40, "weight": 0, "pieces_per_hour_goal": 153 },
    { "client": "PARKER", "name": "TAMPA BEGE INFERIOR", "cavities": 2, "cycle": 40, "weight": 0, "pieces_per_hour_goal": 153 },
    { "client": "PARKER", "name": "BOCAL P/ FILTRO / PISTÃO", "cavities": 4, "cycle": 23, "weight": 0, "pieces_per_hour_goal": 532 },
    { "client": "PARKER", "name": "CÔNICO", "cavities": 1, "cycle": 60, "weight": 0, "pieces_per_hour_goal": 51 },
    { "client": "PARKER", "name": "TURBINA 1", "cavities": 1, "cycle": 60, "weight": 0, "pieces_per_hour_goal": 51 },
    { "client": "PARKER", "name": "TURBINA 2", "cavities": 1, "cycle": 60, "weight": 0, "pieces_per_hour_goal": 51 },
    { "client": "PARKER", "name": "ADAPTADOR", "cavities": 2, "cycle": 18, "weight": 0, "pieces_per_hour_goal": 340 },
    { "client": "PARKER", "name": "TAMPA PLÁSTICA S/ FURO", "cavities": 4, "cycle": 21, "weight": 0, "pieces_per_hour_goal": 583 },
    { "client": "PARKER", "name": "TAMPA PLÁSTICA C/ FURO", "cavities": 4, "cycle": 21, "weight": 0, "pieces_per_hour_goal": 583 },
    { "client": "PARKER", "name": "SUPORTE DO COPO - 6 CAVS - NOVO", "cavities": 6, "cycle": 50, "weight": 0, "pieces_per_hour_goal": 367 },
    { "client": "PARKER", "name": "SUPORTE ESCAL 600", "cavities": 4, "cycle": 50, "weight": 0, "pieces_per_hour_goal": 245 },
    { "client": "PARKER", "name": "SUPORTE R260", "cavities": 4, "cycle": 50, "weight": 0, "pieces_per_hour_goal": 245 },
    { "client": "PARKER", "name": "TAMPA 4 CAVIDADES", "cavities": 4, "cycle": 50, "weight": 0, "pieces_per_hour_goal": 245 },
    { "client": "PARKER", "name": "TAMPA 5923", "cavities": 4, "cycle": 40, "weight": 0, "pieces_per_hour_goal": 306 },
    { "client": "PARKER", "name": "TAMPA 5831", "cavities": 4, "cycle": 35, "weight": 0, "pieces_per_hour_goal": 349 },
    { "client": "PARKER", "name": "COROA P/ FILTRO", "cavities": 2, "cycle": 18, "weight": 0, "pieces_per_hour_goal": 340 },
    { "client": "PARKER", "name": "PLUG 1/4", "cavities": 1, "cycle": 20, "weight": 0, "pieces_per_hour_goal": 153 },
    { "client": "PARKER", "name": "PUXADOR COM BOMBA", "cavities": 2, "cycle": 60, "weight": 0, "pieces_per_hour_goal": 102 },
    { "client": "PARKER", "name": "PLUG 1/2", "cavities": 1, "cycle": 20, "weight": 0, "pieces_per_hour_goal": 153 },
    { "client": "PARKER", "name": "CONJUNTO TAMPÃO", "cavities": 2, "cycle": 20, "weight": 0, "pieces_per_hour_goal": 306 },
    { "client": "PARKER", "name": "PLUG DO DRENO", "cavities": 2, "cycle": 30, "weight": 0, "pieces_per_hour_goal": 204 },
    { "client": "PARKER", "name": "CORPO DO DRENO", "cavities": 2, "cycle": 50, "weight": 0, "pieces_per_hour_goal": 122 },
    { "client": "PARKER", "name": "TAMPÃO PLÁSTICO", "cavities": 4, "cycle": 18, "weight": 0, "pieces_per_hour_goal": 680 },
    { "client": "PARKER", "name": "SUPORTE USINADO INJETADO", "cavities": 2, "cycle": 30.4, "weight": 0, "pieces_per_hour_goal": 201 },
    { "client": "A.S TECHNOLOGY", "name": "TAMPA TUBO EXTERNO", "cavities": 4, "cycle": 30, "weight": 0, "pieces_per_hour_goal": 408 },
    { "client": "A.S TECHNOLOGY", "name": "TAMPA FLIP-TOP TUBO", "cavities": 4, "cycle": 32, "weight": 0, "pieces_per_hour_goal": 382 },
    { "client": "A.S TECHNOLOGY", "name": "MOLDE TUBO EXTERNO", "cavities": 4, "cycle": 35, "weight": 0, "pieces_per_hour_goal": 349 },
    { "client": "ROSEMBERG", "name": "BASE CASSETE", "cavities": 1, "cycle": 55, "weight": 0, "pieces_per_hour_goal": 55 },
    { "client": "ROSEMBERG", "name": "TAMPA CASSETE", "cavities": 1, "cycle": 55, "weight": 0, "pieces_per_hour_goal": 55 },
    { "client": "SUNVISOR", "name": "PRATO DESCARTÁVEL", "cavities": 4, "cycle": 9, "weight": 0, "pieces_per_hour_goal": 1360 },
    { "client": "SUNVISOR", "name": "COMEDOR CATBOWL", "cavities": 1, "cycle": 45, "weight": 0, "pieces_per_hour_goal": 68 },
    { "client": "LH COLUS", "name": "BASE TRIANGULAR - KG3 - SK4647", "cavities": 1, "cycle": 60, "weight": 0, "pieces_per_hour_goal": 51 },
    { "client": "LH COLUS", "name": "JUNÇÃO SEM FURO - KG2 - SK4732", "cavities": 1, "cycle": 60, "weight": 0, "pieces_per_hour_goal": 51 },
    { "client": "LH COLUS", "name": "CORREDIÇA FUNDO VAZADO 6M SEM FURO - KG 4B - SK4763", "cavities": 1, "cycle": 60, "weight": 0, "pieces_per_hour_goal": 51 },
    { "client": "LH COLUS", "name": "CORREDIÇA FUNDO VAZADO 3M SEM FURO - KG 1B - SK4764", "cavities": 1, "cycle": 60, "weight": 0, "pieces_per_hour_goal": 51 },
    { "client": "LH COLUS", "name": "FIXADOR FUNDO FECHADO 3M SEM FURO - KG 1A - SK4766", "cavities": 1, "cycle": 60, "weight": 0, "pieces_per_hour_goal": 51 },
    { "client": "LH COLUS", "name": "FIXADOR FUNDO FECHADO 6M SEM FURO - KG 4A - SK4769", "cavities": 1, "cycle": 60, "weight": 0, "pieces_per_hour_goal": 51 },
    { "client": "LH COLUS", "name": "MANOPLA MACA (HANDLER)", "cavities": 1, "cycle": 60, "weight": 0, "pieces_per_hour_goal": 51 },
    { "client": "LH COLUS", "name": "SHIM SUPPORT LITTER (SUPORTE CALÇO MACA)", "cavities": 1, "cycle": 60, "weight": 0, "pieces_per_hour_goal": 51 },
    { "client": "LH COLUS", "name": "CEILING RING NYLON", "cavities": 1, "cycle": 30, "weight": 0, "pieces_per_hour_goal": 102 },
    { "client": "LH COLUS", "name": "BARRA TRIPLA CORREDIÇA (SLIDE THREE BAR )", "cavities": 1, "cycle": 30, "weight": 0, "pieces_per_hour_goal": 102 },
    { "client": "HOKKAIDO", "name": "TAMPA DO POTE DO SORVETE", "cavities": 1, "cycle": 9, "weight": 0, "pieces_per_hour_goal": 340 },
    { "client": "HOKKAIDO", "name": "POTE DO SORVETE", "cavities": 1, "cycle": 9, "weight": 0, "pieces_per_hour_goal": 340 },
    { "client": "HOKKAIDO", "name": "T - 180/90 - AZUL", "cavities": 8, "cycle": 26, "weight": 0, "pieces_per_hour_goal": 942 },
    { "client": "HOKKAIDO", "name": "I - 180 - VERMELHO", "cavities": 8, "cycle": 26, "weight": 0, "pieces_per_hour_goal": 942 },
    { "client": "INDUSMACK", "name": "SUPORTE REDONDO 3/4\"", "cavities": 6, "cycle": 20, "weight": 0, "pieces_per_hour_goal": 918 },
    { "client": "INDUSMACK", "name": "BOCAL I2", "cavities": 4, "cycle": 80, "weight": 0, "pieces_per_hour_goal": 153 },
    { "client": "INDUSMACK", "name": "BOCAL I3", "cavities": 4, "cycle": 80, "weight": 0, "pieces_per_hour_goal": 153 },
    { "client": "INDUSMACK", "name": "BOCAL I4", "cavities": 4, "cycle": 80, "weight": 0, "pieces_per_hour_goal": 153 },
    { "client": "INDUSMACK", "name": "BOCAL I5", "cavities": 4, "cycle": 80, "weight": 0, "pieces_per_hour_goal": 153 },
    { "client": "INDUSMACK", "name": "BOCAL I6", "cavities": 4, "cycle": 80, "weight": 0, "pieces_per_hour_goal": 153 },
    { "client": "INDUSMACK", "name": "SUPORTE DA MANGUEIRA", "cavities": 4, "cycle": 40, "weight": 0, "pieces_per_hour_goal": 306 },
    { "client": "INDUSMACK", "name": "BICO ENTRADA (ESPIGÃO)", "cavities": 8, "cycle": 40, "weight": 0, "pieces_per_hour_goal": 612 },
    { "client": "INDUSMACK", "name": "SUPORTE REDONDO 1\"", "cavities": 4, "cycle": 30, "weight": 0, "pieces_per_hour_goal": 408 },
    { "client": "GERDAU", "name": "CARRETEL", "cavities": 1, "cycle": 60, "weight": 0, "pieces_per_hour_goal": 51 },
    { "client": "GERDAU", "name": "TRAVA DO CARRETEL", "cavities": 2, "cycle": 22, "weight": 0, "pieces_per_hour_goal": 278 },
    { "client": "CSINFT", "name": "FACE INTERNA", "cavities": 1, "cycle": 42, "weight": 0, "pieces_per_hour_goal": 73 },
    { "client": "JORNADA", "name": "FACE EXTERNA", "cavities": 1, "cycle": 42, "weight": 0, "pieces_per_hour_goal": 73 },
    { "client": "JORNADA", "name": "TAMPÃO", "cavities": 1, "cycle": 42, "weight": 0, "pieces_per_hour_goal": 73 },
    { "client": "JORNADA", "name": "V- 30 CINZA", "cavities": 4, "cycle": 26, "weight": 0, "pieces_per_hour_goal": 471 },
    { "client": "JORNADA", "name": "R - 120 - VERDE", "cavities": 8, "cycle": 26, "weight": 0, "pieces_per_hour_goal": 942 },
    { "client": "JORNADA", "name": "L - 90 - AMARELO", "cavities": 8, "cycle": 26, "weight": 0, "pieces_per_hour_goal": 824 },
    { "client": "JORNADA", "name": "X - 360 - MARROM", "cavities": 4, "cycle": 26, "weight": 0, "pieces_per_hour_goal": 235 }
];
